services:
  nginx:
    image: nginx:latest
    ports:
      - "8082:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/rabbit/nginx:/mnt/logs/nginx
    depends_on:
      - backend
      - frontend
    networks:
      - rabbit_network

  frontend:
    build: 
      context: ./rabbit-fe
    container_name: rabbit-fe
    networks:
      - rabbit_network

  backend:
    build: 
      context: ./rabbit-be
    container_name: rabbit-be
    environment:
      - TZ=Asia/Seoul
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
    networks:
      - rabbit_network

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: rabbit
      MARIADB_USER: rabbit
      MARIADB_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "3306:3306"

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

networks:
  rabbit_network:
    driver: bridge